-- Phase 2: Ingestion Layer for Xentara

-- 1. MONITORED SOURCES
-- These are the "Inputs" for a specific Hub.
CREATE TYPE source_type AS ENUM ('youtube', 'rss', 'rumble', 'twitter', 'manual');

CREATE TABLE IF NOT EXISTS monitored_sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    hub_id UUID NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    type source_type DEFAULT 'youtube',
    url TEXT NOT NULL,
    config JSONB DEFAULT '{}'::jsonb, -- Store whitelist/blacklist rules per source
    last_fetched_at TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true
);

-- Enable RLS on monitored_sources
ALTER TABLE monitored_sources ENABLE ROW LEVEL SECURITY;

-- 2. PUBLICATIONS
-- These are the "Intelligent Output" cards generated by the pipeline.
CREATE TYPE publication_status AS ENUM ('raw', 'transcribing', 'summarizing', 'ready', 'failed');

CREATE TABLE IF NOT EXISTS publications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    hub_id UUID NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
    source_id UUID REFERENCES monitored_sources(id) ON DELETE SET NULL,
    
    -- Content fields
    title TEXT NOT NULL,
    raw_content TEXT, -- Full transcript or original article
    summary TEXT, -- Modern Markdown summary generated by Creative Agent
    byline TEXT, -- 150-char concise summary
    
    -- Intelligence Metadata (Taste Vectors)
    sentiment_score FLOAT, 
    tags TEXT[], -- Topic tags for the Taste Graph
    intelligence_metadata JSONB DEFAULT '{}'::jsonb, -- For specific agent outputs
    
    -- Routing/Status
    status publication_status DEFAULT 'raw',
    source_url TEXT,
    published_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on publications
ALTER TABLE publications ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Sources: Hub Owners can manage their sources
CREATE POLICY "Users can manage sources in their hubs" 
ON monitored_sources FOR ALL 
TO authenticated 
USING (EXISTS (
    SELECT 1 FROM hubs 
    WHERE hubs.id = monitored_sources.hub_id 
    AND hubs.owner_id = auth.uid()
));

-- Publications: Hub Owners can manage publications
CREATE POLICY "Users can manage publications in their hubs" 
ON publications FOR ALL 
TO authenticated 
USING (EXISTS (
    SELECT 1 FROM hubs 
    WHERE hubs.id = publications.hub_id 
    AND hubs.owner_id = auth.uid()
));

-- Triggers for updated_at
CREATE TRIGGER update_monitored_sources_updated_at BEFORE UPDATE ON monitored_sources FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_publications_updated_at BEFORE UPDATE ON publications FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
